
# Node docker image on which this would be run
image: node:latest

cache:
  paths:
    - node_modules/

services:
   - mongo

variables:
  NODE_ENV: 'test'

stages:
  - build
  - test
# Job 1:

install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/

Test:
  stage: test
  script:
    - npm run build:release
