
# Node docker image on which this would be run
image: node:latest

cache:
  paths:
    - node_modules/

services:
   - mongo

variables:
  NODE_ENV: 'test'

stages:
  - build
  - test
  - deploy
# Job 1:

install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/

Test:
  stage: test
  script:
    - npm run test

deploy_staging:
    stage: deploy
    script:
       - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/donations-2019-staging.git
       - git push heroku master
       - echo "Deployed to staging server"
    environment:
      name: staging
      url: https://donations-2019-staging.herokuapp.com/